server {
    listen 80;
    server_name kvest.xamotsorp.space;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kvest.xamotsorp.space;

    ssl_certificate /etc/letsencrypt/live/kvest.xamotsorp.space/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kvest.xamotsorp.space/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /media/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /robots.txt {
        default_type text/plain;
        return 200 "User-agent: *\nDisallow: /\n";
    }
}
